version: "3"
services:

   web_server:
     build:
       context: https://github.com/qiubin8888/docker.git#:lamp
     container_name: lamp
     volumes:
       - ${PWD}/database:/var/lib/mysql
       - ${PWD}:/app
     ports:
       - "3306:3306"
       - "80:80"
     restart: always