version: "3"
services:

   lamp:
     build:
       context: https://github.com/qiubin8888/docker.git#:lamp
       container_name: lamp
       volumes:
         - ${PWD}:/var/lib/mysql
       restart: always